on:
  push:
    branches:
      - main
jobs:
  mac_build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: "3.9"
    - run: pip3 install -U py2app
    - run: python3 setup.py py2app
