on:
  push:
    branches:
      - main
      - macbuild  # just for testing
jobs:
  mac_build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: "3.9"
    - run: pip3 install -U py2app
    - run: python3 setup.py py2app
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v5.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        release_name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}
    - run: ls dist
    - run: ls dist/*
#    - uses: actions/upload-release-asset@v1.0.1
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      with:
#        upload_url: ${{ steps.create_release.outputs.upload_url }}
#        asset_path: what/ever/this/is.app
#        asset_name: Minesweeper_${{ steps.tag_version.outputs.new_tag }}.app
#        asset_content_type: application/octet-stream   # couldn't find anything better
